name: build

on:
    push:
      paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: before_install
      run: |
        sudo apt update
        sudo apt install -y tree git-core gcc g++ make autoconf autoconf-archive automake libtool pkg-config libglib2.0-dev libglibmm-2.4-dev libzip-dev libusb-1.0-0-dev libftdi1-dev libieee1284-3-dev libvisa-dev nettle-dev libavahi-client-dev libhidapi-dev check doxygen python-numpy python-dev python-gi-dev python-setuptools swig default-jdk

    - name: install
      run: |
        true
        echo "install complete"

    - name: script
      id: script
      run: |
        export IDF_PATH=$PWD/ESP8266_RTOS_SDK
        export PATH="$PATH:$PWD/xtensa-lx106-elf/bin"
        ./autogen.sh
        ./configure
        make
        tree -a
        echo "::set-output name=status::success"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output.zip
        path: |
          src
