name: build

on:
    push:
      paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: before_install
      run: |
        sudo apt-get update
        sudo apt-get install -y tree git-core gcc g++ make autoconf autoconf-archive automake libtool pkg-config libglib2.0-dev libglibmm-2.4-dev libzip-dev libusb-1.0-0-dev libftdi1-dev libieee1284-3-dev libvisa-dev nettle-dev libavahi-client-dev libhidapi-dev check doxygen python3-numpy python3-dev python-gi-dev python3-setuptools swig default-jdk
        
    - name: install
      run: |
        echo "install complete"

    - name: script
      id: script
      run: |
        ./autogen.sh
        ./configure --disable-ruby
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: output.zip
        path: |
          **/*.so*
